# This is a basic workflow to help you get started with Actions

name: Jupyter

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '0 */24 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - id: repo
       name: Repo Checkout
       uses: actions/checkout@v2

     - id: python
       name: Python setup & Packages
       uses: actions/setup-python@v4
       with:
        python-version: '3.9'
        cache: 'pip' # caching pip dependencies
     - run: pip install -r requirements.txt

     - id: jupyter
       name: Jupyter Notebook execution
       run: jupyter execute download.ipynb
       shell: bash
    
